'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { CalendarDays, Clock3, MapPin, ShieldCheck, Ticket, Users } from 'lucide-react';
import SiteFooter from '@/components/SiteFooter';

const events: Record<string, { title: string; category: string; date: string; time: string; venue: string; price: number; tone: string; icon: string; description: string }> = {
  'sounds-of-india': { title: 'VIR DAS - SOUNDS OF INDIA - CHENNAI', category: 'Comedy', date: '31 Oct 2026', time: '7:30 PM', venue: 'Sir Mutha Venkatasubba Rao Concert Hall, Chennai', price: 799, tone: 'from-amber-300 via-orange-500 to-red-600', icon: '🎤', description: 'A live comedy experience presented in a cinema-style event discovery flow. Check the listing for venue and ticket information before booking.' },
  'tabla-poetry': { title: 'Tabla Poetry By Bhupendra Singh', category: 'Music', date: '20 Sep 2026', time: '7:00 PM', venue: 'Music Academy Mini Hall, Chennai', price: 499, tone: 'from-violet-950 via-purple-800 to-fuchsia-500', icon: '🥁', description: 'A live music and tabla-focused experience. Explore the event details, venue and ticket options before reserving your place.' },
  'sundance': { title: 'Casa Grand Sundance', category: 'Experiences', date: '17 Sep 2026 onwards', time: 'Multiple slots', venue: 'Casagrand Suncity, Chennai', price: 399, tone: 'from-slate-950 via-cyan-900 to-emerald-400', icon: '✨', description: 'An experience listing for visitors looking for something beyond movies. Select the event to review timing and ticket information.' },
  'kids-running': { title: 'Chennai Kids Running Festival 2026', category: 'Sports', date: '20 Sep 2026', time: 'Morning', venue: 'SDAT - Nehru Park, Chennai', price: 299, tone: 'from-sky-400 via-blue-600 to-indigo-900', icon: '🏃', description: 'A family-friendly running experience. Review the event information and participation details before booking.' },
  'marine-kingdom': { title: 'VGP Marine Kingdom - Chennai', category: 'Activities', date: '17 Sep 2026 onwards', time: 'Multiple slots', venue: 'VGP Marine Kingdom, Chennai', price: 650, tone: 'from-cyan-300 via-blue-700 to-slate-950', icon: '🌊', description: 'Explore an attraction-style experience with date and ticket information presented in the MovieClick interface.' },
  'gokul-insecure': { title: 'Insecure by Gokul Kumar', category: 'Comedy', date: '20 Sep 2026', time: '7:00 PM', venue: 'Medai - The Stage, Alwarpet, Chennai', price: 399, tone: 'from-indigo-950 via-blue-800 to-black', icon: '😂', description: 'A stand-up comedy listing. Choose the date and review ticket details before booking.' },
  'akshay-live': { title: 'Akshay Srivastava Live Standup Comedy', category: 'Comedy', date: '19 Sep 2026', time: '7:30 PM', venue: 'Trinity Studio, Kodambakkam, Chennai', price: 499, tone: 'from-blue-950 via-blue-700 to-slate-900', icon: '🎙️', description: 'A live stand-up comedy experience listed for Chennai audiences.' },
  'clat-tour': { title: 'All India CLAT GK Tour', category: 'Education', date: '20 Sep 2026', time: 'Multiple slots', venue: 'Chennai', price: 249, tone: 'from-emerald-400 via-green-700 to-yellow-300', icon: '📚', description: 'An educational event listing with ticket information and venue details.' },
  'hug-therapy': { title: 'Hug Therapy', category: 'Experiences', date: '17 Sep 2026', time: 'Multiple slots', venue: 'Chennai', price: 499, tone: 'from-lime-300 via-amber-600 to-stone-800', icon: '🤝', description: 'An experience listing available through MovieClick.' },
};

export default function EventInfoPage() {
  const { id } = useParams();
  const event = events[id as string];

  if (!event) return <main className="min-h-screen bg-[#f4f5f7] p-10 text-center dark:bg-[#080b12]"><h1 className="text-2xl font-black">Event not found</h1><Link className="mt-5 inline-block font-bold text-[#e83f57]" href="/discover-events">Back to Events</Link></main>;

  return (
    <main className="min-h-screen bg-[#f4f5f7] dark:bg-[#080b12]">
      <section className={`bg-gradient-to-br ${event.tone} text-white`}>
        <div className="mx-auto max-w-7xl px-5 py-12 md:py-16"><Link href="/discover-events" className="text-sm font-semibold text-white/75 hover:text-white">← Back to Events</Link><div className="mt-10 grid gap-8 md:grid-cols-[280px_1fr] md:items-center"><div className="flex aspect-[4/5] items-center justify-center rounded-3xl bg-black/20 text-[110px] shadow-2xl backdrop-blur">{event.icon}</div><div><span className="rounded-full bg-white/15 px-4 py-2 text-xs font-bold uppercase tracking-wider">{event.category}</span><h1 className="mt-5 max-w-3xl text-4xl font-black leading-tight md:text-6xl">{event.title}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-white/75">{event.description}</p><div className="mt-7 flex flex-wrap gap-3"><span className="rounded-xl bg-white/10 px-4 py-3 text-sm"><CalendarDays className="mr-2 inline h-4 w-4" />{event.date}</span><span className="rounded-xl bg-white/10 px-4 py-3 text-sm"><Clock3 className="mr-2 inline h-4 w-4" />{event.time}</span><span className="rounded-xl bg-white/10 px-4 py-3 text-sm"><MapPin className="mr-2 inline h-4 w-4" />{event.venue}</span></div></div></div></div>
      </section>

      <section className="mx-auto max-w-7xl px-5 py-10"><div className="grid gap-5 lg:grid-cols-[1fr_360px]"><div className="space-y-5"><div className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-black/5 dark:bg-[#111722]"><h2 className="text-xl font-black">Event information</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-xl bg-gray-50 p-4 dark:bg-gray-900"><CalendarDays className="h-5 w-5 text-[#e83f57]" /><p className="mt-2 text-xs text-gray-500">Date</p><p className="font-bold">{event.date}</p></div><div className="rounded-xl bg-gray-50 p-4 dark:bg-gray-900"><Clock3 className="h-5 w-5 text-[#e83f57]" /><p className="mt-2 text-xs text-gray-500">Time</p><p className="font-bold">{event.time}</p></div><div className="rounded-xl bg-gray-50 p-4 dark:bg-gray-900 sm:col-span-2"><MapPin className="h-5 w-5 text-[#e83f57]" /><p className="mt-2 text-xs text-gray-500">Venue</p><p className="font-bold">{event.venue}</p></div></div></div><div className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-black/5 dark:bg-[#111722]"><h2 className="text-xl font-black">Good to know</h2><ul className="mt-4 space-y-3 text-sm text-gray-500"><li>• Check your ticket details before completing the booking.</li><li>• Keep your confirmation available at the venue.</li><li>• Event timing and availability can change.</li></ul></div></div><aside className="h-fit rounded-2xl bg-white p-6 shadow-lg ring-1 ring-black/5 dark:bg-[#111722]"><div className="flex items-center gap-3"><Ticket className="h-5 w-5 text-[#e83f57]" /><span className="font-bold">Tickets from</span></div><p className="mt-2 text-3xl font-black">₹{event.price}</p><p className="mt-1 text-xs text-gray-500">per ticket · demo listing</p><Link href="/events" className="mt-6 flex w-full items-center justify-center rounded-xl bg-[#e83f57] px-5 py-3.5 font-bold text-white transition hover:bg-[#d9364f]">Browse Movie Tickets</Link><div className="mt-5 flex gap-2 text-xs text-gray-500"><ShieldCheck className="h-4 w-4 text-green-600" /> Secure MovieClick account flow</div><div className="mt-4 flex gap-2 text-xs text-gray-500"><Users className="h-4 w-4" /> Group-friendly discovery</div></aside></div></section>
      <SiteFooter />
    </main>
  );
}
